serve:
  playground: true
  browser: false
require:
  - ts-node/register/transpile-only
additionalTypeDefs: |
  extend type Vehicle {
    isOwnedByAlkemics: Boolean
  }
additionalResolvers:
  - ./src/custom-resolvers.ts  
sources:
  - name: Service Demo
    handler:
      openapi:
        source: ./service-demo-openapi.json
        baseUrl: ${DEMO_APP_URL}
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  - name: Swapi
    handler:
      graphql:
        endpoint: https://swapi-graphql.netlify.app/.netlify/functions/index
  - name: SpaceX
    handler:
      graphql:
        endpoint: https://api.spacex.land/graphql/
transforms:
  - rename: 
      mode: wrap 
      renames:
        - from:
            type: Query
            field: getDemoUsersV1UserIdGet
          to:
            type: Query
            field: getUser

