serve:
  playground: false
  browser: false
require:
  - ts-node/register/transpile-only
additionalResolvers:
  - ./src/custom-resolvers.ts  
additionalTypeDefs: |
  extend type User {
    isAlkemicsAdmin: Boolean
    recentOrders: [Order]
  }
sources:
  - name: Service Demo
    handler:
      openapi:
        source: ./service-demo-openapi.json
        baseUrl: http://127.0.0.1:8000/
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  - name: FakeQL Shop
    handler:
      graphql:
        endpoint: https://fakeql.com/graphql/cade9579438de114c305c686f8936d49
transforms:
  - rename: 
      mode: wrap 
      renames:
        - from:
            type: Query
            field: getDemoUsersV1UserIdGet
          to:
            type: Query
            field: getUser
